# Generated by Django 3.2.7 on 2021-09-20 17:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='category')),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=100, null=True)),
                ('image', models.ImageField(default='team/chef.png', null=True, upload_to='team')),
                ('description', models.TextField(null=True)),
                ('s_facebook', models.CharField(blank=True, max_length=100, null=True)),
                ('s_twitter', models.CharField(blank=True, max_length=100, null=True)),
                ('s_in', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='product')),
                ('price', models.FloatField(default=0)),
                ('discount', models.FloatField(default=0)),
                ('status', models.CharField(choices=[('meal', 'meal'), ('NONE', 'NONE'), ('drink', 'drink'), ('dessert', 'dessert')], default='NONE', max_length=50)),
                ('description', models.TextField(null=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.category')),
            ],
        ),
    ]
